Database:
  DbType: mysql
  DbName: go-chain-data
  Host: 127.0.0.1:3306
  Username: root
  Pwd: 123456
  Charset: utf8
  ParseTime: True

BlockChain:
  RpcUrl: HTTP://127.0.0.1:7545   #  区块链rpc地址  infura.io 可以获取
